In [ ]:
!pip install simpledbf

Collecting simpledbf
  Downloading simpledbf-0.2.6.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simpledbf
  Building wheel for simpledbf (setup.py) ... done
  Created wheel for simpledbf: filename=simpledbf-0.2.6-py3-none-any.whl size=13786 sha256=420c621c53f60e52458a3843a323d7f3eb9772721dff9adf84b87a4bf6d37683
  Stored in directory: /root/.cache/pip/wheels/7d/53/e7/7002aa67a7d1ff157663e0009d2ff1735020a669a5034c7ba4
Successfully built simpledbf
Installing collected packages: simpledbf
Successfully installed simpledbf-0.2.6

In [ ]:
import pandas as pd
import numpy as np
from simpledbf import Dbf5

In [ ]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [ ]:
def leerDBF(path_):
    Dbf = Dbf5(path_, codec='cp850')
    df = Dbf.to_dataframe()
    return df

# 1. Información cualitativa sobre el proyecto Mente Sana durante el 2025

In [ ]:
df_ong = pd.read_csv('/content/MS2025-Sistematización - IIEE.csv', dtype='str')

In [ ]:
df_ong.head()

,Institución educativa,UGT,Provincia,Distrito,Centro Poblado,Cod modular,Cod local,Nivel modular
0,88059,HUARMEY,HUARMEY,HUARMEY,9 DE OCTUBRE,0476531,025996,Primaria
1,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0606913,026095,Secundaria
2,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0343640,026095,Primaria
3,86357,MINA,HUARI,SAN PEDRO DE CHANA,SANTA CRUZ DE PICHIU,0414094,025623,Primaria
4,86843,MINA,HUARI,SAN PEDRO DE CHANA,HUANCAYOC,0542662,025642,Primaria

# 2. Padrón Web

In [ ]:
pathPadronWeb = '/content/drive/MyDrive/Clases/Proyecto Aplicado/Educación/Padrón Web/Padron_web.dbf'

In [ ]:
df_padron_web = leerDBF(pathPadronWeb)

In [ ]:
df_padron_web.head(3)

,CODINST,COD_MOD,ANEXO,CODLOCAL,CEN_EDU,NIV_MOD,D_NIV_MOD,D_FORMA,COD_CAR,D_COD_CAR,TIPSSEXO,D_TIPSSEXO,GESTION,D_GESTION,GES_DEP,D_GES_DEP,DIRECTOR,TELEFONO,EMAIL,PAGWEB,DIR_CEN,LOCALIDAD,CODCP_INEI,CODCCPP,CEN_POB,AREA_CENSO,DAREACENSO,CODGEO,D_DPTO,D_PROV,D_DIST,D_REGION,CODOOII,D_DREUGEL,NLAT_IE,NLONG_IE,TIPOPROG,D_TIPOPROG,COD_TUR,D_COD_TUR,NRORUC,RZSOCIAL,PROMOTOR,ESTADO,D_ESTADO,D_FTE_DATO,TALUM_HOM,TALUM_MUJ,TALUMNO,TDOCENTE,TSECCION,FECHAREG,FECHA_ACT
0,24953981,0415547,0,016100,123,A2,Inicial - Jardín,Escolarizada,a,No aplica,3,Mixto,1,Pública de gestión directa,A1,Sector Educación,CACERES DE MAUTINO YONNY ESCOLASTICA,NaN,NaN,NaN,JIRON TERESA GONZALES DE FANNY 543,NICRUPAMPA,0201050001,129688,CENTENARIO,1,Urbana,020105,ANCASH,HUARAZ,INDEPENDENCIA,DRE ANCASH,020001,UGEL HUARAZ,-9.51885,-77.53191,NaN,NaN,11,Mañana,NaN,NaN,NaN,1,Activo,Declarado,214,219,433,17,16,NaN,05-01-2026
1,25273230,0415638,0,015172,122,A2,Inicial - Jardín,Escolarizada,a,No aplica,3,Mixto,1,Pública de gestión directa,A1,Sector Educación,CACERES DE MAUTINO YONNY ESCOLASTICA,043-420252,NaN,NaN,JIRON 28 DE JULIO S/N,HUARUPAMPA,0201010001,114517,HUARUPAMPA,1,Urbana,020101,ANCASH,HUARAZ,HUARAZ,DRE ANCASH,020001,UGEL HUARAZ,-9.53067,-77.53196,NaN,NaN,11,Mañana,NaN,NaN,NaN,1,Activo,Declarado,246,222,468,19,18,02-05-1942,05-01-2026
2,20414731,0415646,0,015186,233,A2,Inicial - Jardín,Escolarizada,a,No aplica,3,Mixto,1,Pública de gestión directa,A1,Sector Educación,LOPEZ MONGE MARIA ESTHER MONICA,043-427649-943940593,NaN,NaN,JIRON AMADEO FIGUEROA S/N,NaN,NaN,610619,LA SOLEDAD,1,Urbana,020101,ANCASH,HUARAZ,HUARAZ,DRE ANCASH,020001,UGEL HUARAZ,-9.53110,-77.52270,NaN,NaN,13,Mañana-Tarde,NaN,NaN,NaN,1,Activo,Declarado,272,274,546,24,22,04-08-1974,05-01-2026

## Cruce

In [ ]:
columnas = ['COD_MOD', 'D_NIV_MOD', 'D_TIPSSEXO', 'D_GESTION', 'TALUMNO', 'TDOCENTE']

In [ ]:
df_ong = pd.merge(df_ong, df_padron_web[columnas], left_on='Cod modular', right_on='COD_MOD', how='left')

In [ ]:
df_ong.head()

,Institución educativa,UGT,Provincia,Distrito,Centro Poblado,Cod modular,Cod local,Nivel modular,COD_MOD,D_NIV_MOD,D_TIPSSEXO,D_GESTION,TALUMNO,TDOCENTE
0,88059,HUARMEY,HUARMEY,HUARMEY,9 DE OCTUBRE,0476531,025996,Primaria,0476531,Primaria,Mixto,Pública de gestión directa,27.0,2.0
1,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0606913,026095,Secundaria,0606913,Secundaria,Mixto,Pública de gestión directa,86.0,9.0
2,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0343640,026095,Primaria,0343640,Primaria,Mixto,Pública de gestión directa,122.0,7.0
3,86357,MINA,HUARI,SAN PEDRO DE CHANA,SANTA CRUZ DE PICHIU,0414094,025623,Primaria,0414094,Primaria,Mixto,Pública de gestión directa,6.0,1.0
4,86843,MINA,HUARI,SAN PEDRO DE CHANA,HUANCAYOC,0542662,025642,Primaria,0542662,Primaria,Mixto,Pública de gestión directa,120.0,7.0

# 3. Censo Educativo - Ejemplo: Matrícula

In [ ]:
path_matricula_1 = '/content/drive/MyDrive/Clases/Proyecto Aplicado/Educación/Censo Educativo/Matricula_01.dbf'

In [ ]:
df_matricula_1 = leerDBF(path_matricula_1)

In [ ]:
df_matricula_1.head(5)

,IMPUTADO,COD_MOD,NROCED,TIPOPROG,FORMATEN,CUADRO,BLOQUE,TIPDATO,CODSEDE,MODALIDAD,CTRL_CNEE,D01,D02,D03,D04,D05,D06,D07,D08,D09,D10,D11,D12,D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,D25,D26,D27,D28,D29,D30,NIV_MOD,GES_DEP,CODGEO,CODOOII,AREA_CENSO,CODLOCAL,ANEXO
0,1_INFORMANTE,1532258,3AP,NaN,S,C201,-,01,NaN,NaN,NaN,9.0,12.0,9.0,11.0,10,9,13,7,9,12,6,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,B0,B4,050101,050001,1,572773,0
1,1_INFORMANTE,1509009,3AP,NaN,S,C201,-,01,NaN,NaN,NaN,17.0,9.0,12.0,12.0,17,11,16,12,16,9,11,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,B0,B4,150103,150107,1,721476,0
2,1_INFORMANTE,0821132,3AP,NaN,S,C201,-,01,NaN,NaN,NaN,1.0,1.0,0.0,1.0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,B0,B4,150135,150103,1,336149,0
3,1_INFORMANTE,1613983,1A,NaN,S,C201,-,01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,A2,A1,210602,210006,2,678086,0
4,1_INFORMANTE,0217380,1A,NaN,S,C201,-,01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0,0,1,0,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,A2,B4,150135,150103,1,336149,0

## Primaria

In [ ]:
df_ong_primaria = df_ong[df_ong['Nivel modular'] == 'Primaria'].copy()

In [ ]:
df_ong_primaria.shape

(15, 14)

In [ ]:
columnas = ['COD_MOD', 'D01', 'D02', 'D03', 'D04', 'D05', 'D06', 'D07', 'D08', 'D09', 'D10', 'D11', 'D12']

In [ ]:
df_ong_primaria = pd.merge(df_ong_primaria, df_matricula_1[columnas], on='COD_MOD', how='left')

In [ ]:
df_ong_primaria.head(100)

,Institución educativa,UGT,Provincia,Distrito,Centro Poblado,Cod modular,Cod local,Nivel modular,COD_MOD,D_NIV_MOD,D_TIPSSEXO,D_GESTION,TALUMNO,TDOCENTE,D01,D02,D03,D04,D05,D06,D07,D08,D09,D10,D11,D12
0,88059,HUARMEY,HUARMEY,HUARMEY,9 DE OCTUBRE,0476531,025996,Primaria,0476531,Primaria,Mixto,Pública de gestión directa,27.0,2.0,1.0,3.0,4.0,3.0,0,3,1,3,3,2,0,0
1,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0343640,026095,Primaria,0343640,Primaria,Mixto,Pública de gestión directa,122.0,7.0,7.0,10.0,13.0,7.0,5,11,9,8,8,8,14,9
2,86357,MINA,HUARI,SAN PEDRO DE CHANA,SANTA CRUZ DE PICHIU,0414094,025623,Primaria,0414094,Primaria,Mixto,Pública de gestión directa,6.0,1.0,2.0,1.0,0.0,1.0,2,1,0,2,0,0,0,0
3,86843,MINA,HUARI,SAN PEDRO DE CHANA,HUANCAYOC,0542662,025642,Primaria,0542662,Primaria,Mixto,Pública de gestión directa,120.0,7.0,14.0,8.0,8.0,12.0,7,13,11,15,9,11,12,13
4,86901,MINA,HUARI,HUACHIS,SAN CRISTOBAL DE TAMBO,0597872,024464,Primaria,0597872,Primaria,Mixto,Pública de gestión directa,13.0,2.0,1.0,2.0,1.0,0.0,0,1,0,3,1,1,1,2
5,86906,MINA,HUARI,SAN PEDRO DE CHANA,VISTOSO,0645010,025680,Primaria,0645010,Primaria,Mixto,Pública de gestión directa,80.0,7.0,3.0,10.0,7.0,9.0,8,7,9,2,7,6,7,9
6,TECNICO INDUSTRIAL,MINA,HUARI,SAN MARCOS,AYASH HUARIPAMPA,1795707,526724,Primaria,1795707,Primaria,Mixto,Pública de gestión directa,20.0,3.0,1.0,1.0,1.0,2.0,1,2,1,3,2,2,0,5
7,86944,MINA,HUARI,HUACHIS,AYASH PICHIU,0681346,024483,Primaria,0681346,Primaria,Mixto,Pública de gestión directa,38.0,4.0,10.0,6.0,6.0,3.0,3,4,1,2,2,3,6,2
8,20851,VALLE FORTALEZA,BOLOGNESI,COLQUIOC,LLAMPA,0247668,019655,Primaria,0247668,Primaria,Mixto,Pública de gestión directa,20.0,3.0,1.0,0.0,10.0,3.0,0,3,1,2,0,0,1,0
9,86260,VALLE FORTALEZA,BOLOGNESI,CAJACAY,COLCA,0411447,019599,Primaria,0411447,Primaria,Mixto,Pública de gestión directa,20.0,3.0,2.0,2.0,2.0,2.0,3,0,2,0,1,0,3,1
10,20850 MARISCAL CACERES,VALLE FORTALEZA,BOLOGNESI,COLQUIOC,CHASQUITAMBO,0247650,019641,Primaria,0247650,Primaria,Mixto,Pública de gestión directa,184.0,10.0,14.0,14.0,17.0,19.0,15,21,11,19,19,22,20,15
11,86221 SAN AGUSTIN,VALLE FORTALEZA,BOLOGNESI,CAJACAY,CAJACAY,0415513,019561,Primaria,0415513,Primaria,Mixto,Pública de gestión directa,59.0,6.0,4.0,4.0,7.0,2.0,6,8,5,4,4,3,4,6
12,86244 LUIS PARDO NOVOA,VALLE FORTALEZA,BOLOGNESI,ANTONIO RAYMONDI,RAQUIA,0411397,019392,Primaria,0411397,Primaria,Mixto,Pública de gestión directa,61.0,14.0,8.0,6.0,9.0,3.0,5,6,3,2,5,9,3,4
13,86567 SAN JUAN DE PARARIN,VALLE FORTALEZA,RECUAY,PARARIN,RINCONADA,0415166,033543,Primaria,0415166,Primaria,Mixto,Pública de gestión directa,68.0,6.0,0.0,1.0,3.0,4.0,5,5,8,4,5,6,7,6
14,86974 ISABEL FLORES DE OLIVA,VALLE FORTALEZA,BOLOGNESI,CAJACAY,SANTA ROSA,0735720,019617,Primaria,0735720,Primaria,Mixto,Pública de gestión directa,49.0,5.0,2.0,2.0,1.0,2.0,4,3,2,3,8,6,0,4

- D01 N (6) 1° grado, hombre 999999
- D02 N (6) 1° grado, mujer 999999
- D03 N (6) 2° grado, hombre 999999
- D04 N (6) 2° grado, mujer 999999
- D05 N (6) 3° grado, hombre 999999
- D06 N (6) 3° grado, mujer 999999
- D07 N (6) 4° grado, hombre 999999
- D08 N (6) 4° grado, mujer 999999
- D09 N (6) 5° grado, hombre 999999
- D10 N (6) 5° grado, mujer 999999
- D11 N (6) 6° grado, hombre 999999
- D12 N (6) 6° grado, mujer 999999

## Secundaria

In [ ]:
df_ong_secundaria = df_ong[df_ong['Nivel modular'] == 'Secundaria'].copy()

In [ ]:
columnas = ['COD_MOD', 'D01', 'D02', 'D03', 'D04', 'D05', 'D06', 'D07', 'D08', 'D09', 'D10']

In [ ]:
df_ong_secundaria = pd.merge(df_ong_secundaria, df_matricula_1[columnas], on='COD_MOD', how='left')

In [ ]:
df_ong_secundaria.head(100)

,Institución educativa,UGT,Provincia,Distrito,Centro Poblado,Cod modular,Cod local,Nivel modular,COD_MOD,D_NIV_MOD,D_TIPSSEXO,D_GESTION,TALUMNO,TDOCENTE,D01,D02,D03,D04,D05,D06,D07,D08,D09,D10
0,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0606913,026095,Secundaria,0606913,Secundaria,Mixto,Pública de gestión directa,86.0,9.0,12.0,13.0,7.0,13.0,9.0,10.0,13.0,8.0,7.0,7.0
1,86906,MINA,HUARI,SAN PEDRO DE CHANA,VISTOSO,\t1396092,025680,Secundaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20851,VALLE FORTALEZA,BOLOGNESI,COLQUIOC,LLAMPA,1090851,019655,Secundaria,1090851,Secundaria,Mixto,Pública de gestión directa,16.0,9.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,0.0,3.0,2.0
3,20850 MARISCAL CACERES,VALLE FORTALEZA,BOLOGNESI,COLQUIOC,CHASQUITAMBO,0577270,019641,Secundaria,0577270,Secundaria,Mixto,Pública de gestión directa,192.0,18.0,24.0,16.0,20.0,17.0,28.0,23.0,22.0,13.0,17.0,20.0
4,86221 SAN AGUSTIN,VALLE FORTALEZA,BOLOGNESI,CAJACAY,CAJACAY,0411850,019561,Secundaria,0411850,Secundaria,Mixto,Pública de gestión directa,58.0,9.0,9.0,5.0,9.0,4.0,7.0,3.0,6.0,6.0,7.0,7.0
5,86244 LUIS PARDO NOVOA,VALLE FORTALEZA,BOLOGNESI,ANTONIO RAYMONDI,RAQUIA,0597609,019392,Secundaria,0597609,Secundaria,Mixto,Pública de gestión directa,106.0,8.0,10.0,11.0,8.0,12.0,9.0,15.0,7.0,12.0,12.0,8.0
6,86567 SAN JUAN DE PARARIN,VALLE FORTALEZA,RECUAY,PARARIN,RINCONADA,0681478,033543,Secundaria,0681478,Secundaria,Mixto,Pública de gestión directa,68.0,9.0,8.0,9.0,8.0,10.0,4.0,6.0,4.0,6.0,6.0,4.0
7,86974 ISABEL FLORES DE OLIVA,VALLE FORTALEZA,BOLOGNESI,CAJACAY,SANTA ROSA,1102003,019617,Secundaria,1102003,Secundaria,Mixto,Pública de gestión directa,39.0,8.0,13.0,4.0,8.0,5.0,8.0,7.0,3.0,4.0,3.0,4.0

- D01 N (6) 1° grado, hombre 999999
- D02 N (6) 1° grado, mujer 999999
- D03 N (6) 2° grado, hombre 999999
- D04 N (6) 2° grado, mujer 999999
- D05 N (6) 3° grado, hombre 999999
- D06 N (6) 3° grado, mujer 999999
- D07 N (6) 4° grado, hombre 999999
- D08 N (6) 4° grado, mujer 999999
- D09 N (6) 5° grado, hombre 999999
- D10 N (6) 5° grado, mujer 999999

# 4. Local Educativo

### Aulas

In [ ]:
path_aulas = '/content/drive/MyDrive/Clases/Proyecto Aplicado/Educación/Censo Educativo/Loc_P61_Aulas.dbf'

In [ ]:
df_aulas = leerDBF(path_aulas)

In [ ]:
df_aulas.head()

,CODLOCAL,NROCED,CUADRO,NUMERO,ID_EDIF,P61_2,P61_3,P61_4,P61_5_11,P61_5_12,P61_5_13,P61_5_14,P61_5_21,P61_5_22,P61_5_23,P61_5_24,P61_5_31,P61_5_32,P61_5_33,P61_5_34,P61_5_4,P61_6,P61_7_1,P61_7_2,P61_7_3,P61_8,P61_9_1,P61_9_2,P61_9_3,P61_9_4,P61_10_1,P61_10_2,P61_11_1,P61_11_2,P61_11_3,P61_11_4,P61_11_5,P61_11_6,P61_12_1,P61_12_2,P61_13_1,P61_13_2,P61_14_1,P61_14_2,P61_15_1,P61_15_2,P61_16_1,P61_16_2,P61_16_3,P61_16_4,P61_17_1,P61_17_2,P61_17_3,P61_17_4,P61_18,P61_19,P61_20_1,P61_20_2,P61_20_3,P61_20_4,P61_21_1,P61_21_2,P61_21_3,P61_21_4,P61_21_5,P61_22_11,P61_22_12,P61_22_13,P61_22_21,P61_22_22,P61_22_23,P61_22_31,P61_22_32,P61_22_33,P61_22_41,P61_22_42,P61_22_43,P61_22_51,P61_22_52,P61_22_53,P61_22_61,P61_22_62,P61_22_63,P61_22_71,P61_22_72,P61_22_73,P61_22_81,P61_22_82,P61_22_83,P61_22_91,P61_22_92,P61_22_93,FEC_ENVIO,GESTION,ANEXO,AREA_CENSO
0,000019,11,C061,1,E01,1,1,02,A2,3,NaN,16,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,1,6.2,5.0,3.0,1,1,01,MA,1.0,1,RE,6,01,MA,1,RE,NA,01,RE,10,MA,03,RE,1,MA,0,0,0,0,6.0,0,4,2,0,0,16,8,6,2,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,2025-09-15 11:02:09,1,0,1
1,000019,11,C061,2,E01,1,1,02,A2,5,NaN,23,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,1,6.2,5.8,3.0,1,1,01,MA,1.0,1,RE,6,01,MA,1,RE,NA,01,RE,10,MA,03,RE,1,MA,0,0,0,0,6.0,0,5,1,0,0,23,0,23,0,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,2025-09-15 11:02:09,1,0,1
2,000019,11,C061,3,E01,1,1,02,A2,5,NaN,20,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,1,5.8,4.2,3.0,1,1,01,MA,1.0,1,RE,4,01,MA,1,RE,NA,01,RE,10,MA,03,RE,1,MA,0,0,0,0,4.0,4,0,0,0,0,20,0,20,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,2025-09-15 11:02:09,1,0,1
3,000019,11,C061,4,E01,1,1,02,A2,3,NaN,17,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,1,5.2,4.2,3.0,1,1,01,MA,1.0,1,RE,4,01,MA,1,RE,NA,01,RE,10,MA,03,RE,1,MA,0,0,0,0,4.0,0,4,0,0,0,17,0,17,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,2025-09-15 11:02:09,1,0,1
4,000019,11,C061,5,E01,1,1,02,A2,4,NaN,22,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,1,6.0,4.2,3.0,1,1,01,MA,1.0,1,RE,6,01,MA,1,RE,NA,01,RE,10,MA,03,RE,1,MA,0,0,0,0,6.0,6,0,0,0,0,22,0,22,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,2025-09-15 11:02:09,1,0,1

- P61_3: 3.1. ¿El ambiente se encuentra en uso?
- P61_4: 4. Este ambiente es de:
- P61_12_1: 12. Paredes / 1. Material Predominante
- P61_12_2: 12. Paredes
    2. Estado de Conservación
         BU: Bueno
         RE: Regular
         MA: Malo
         NA: No Aplica
- P61_13_1: 13. Techo / 1. Material Predominante
- P61_13_2: 13. Techo
    2. Estado de Conservación
         BU: Bueno
         RE: Regular
         MA: Malo
         NA: No Aplica
- P61_14_1: 14. Piso / 1. Material Predominante
- P61_14_2: 14. Piso
    2. Estado de Conservación
         BU: Bueno
         RE: Regular
         MA: Malo
         NA: No Aplica

- P61_15_1: 15. Instalaciones Eléctricas / 1. ¿Tiene?
- P61_16_1: 16. Mesas Unipersonales
    1. Cantidad Total
- P61_20_1: 20. Sillas
    1. Cantidad Total
- P61_21_1: 21. Pizarras / 1. Cantidad Total

In [ ]:
columnas = ['CODLOCAL', 'CUADRO', 'NUMERO', 'ID_EDIF', 'P61_3', 'P61_4', 'P61_12_1', 'P61_12_2', 'P61_13_1', 'P61_13_2', 'P61_14_1', 'P61_14_2', 'P61_15_1', 'P61_16_1', 'P61_20_1', 'P61_21_1']

#### Tomamos la primera institución de ejemplo (Cod local = '025996')

In [ ]:
df_ong.head()

,Institución educativa,UGT,Provincia,Distrito,Centro Poblado,Cod modular,Cod local,Nivel modular,COD_MOD,D_NIV_MOD,D_TIPSSEXO,D_GESTION,TALUMNO,TDOCENTE
0,88059,HUARMEY,HUARMEY,HUARMEY,9 DE OCTUBRE,0476531,025996,Primaria,0476531,Primaria,Mixto,Pública de gestión directa,27.0,2.0
1,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0606913,026095,Secundaria,0606913,Secundaria,Mixto,Pública de gestión directa,86.0,9.0
2,INDUSTRIAL PILOTO MIGUEL GRAU,HUARMEY,HUARMEY,HUARMEY,PUERTO HUARMEY,0343640,026095,Primaria,0343640,Primaria,Mixto,Pública de gestión directa,122.0,7.0
3,86357,MINA,HUARI,SAN PEDRO DE CHANA,SANTA CRUZ DE PICHIU,0414094,025623,Primaria,0414094,Primaria,Mixto,Pública de gestión directa,6.0,1.0
4,86843,MINA,HUARI,SAN PEDRO DE CHANA,HUANCAYOC,0542662,025642,Primaria,0542662,Primaria,Mixto,Pública de gestión directa,120.0,7.0

In [ ]:
df_aulas[df_aulas['CODLOCAL'] == '025996'][columnas]

,CODLOCAL,CUADRO,NUMERO,ID_EDIF,P61_3,P61_4,P61_12_1,P61_12_2,P61_13_1,P61_13_2,P61_14_1,P61_14_2,P61_15_1,P61_16_1,P61_20_1,P61_21_1
11115,025996,C061,1,E01,1,01,01,BU,01,BU,03,BU,1,0,8,1
11116,025996,C061,2,E01,1,01,01,BU,01,BU,04,BU,1,0,16,1
11117,025996,C061,3,E03,1,01,01,RE,05,RE,03,RE,1,0,16,1

#### Tomamos la segunda institución de ejemplo (Cod local = '026095')

In [ ]:
df_aulas[df_aulas['CODLOCAL'] == '026095'][columnas]

,CODLOCAL,CUADRO,NUMERO,ID_EDIF,P61_3,P61_4,P61_12_1,P61_12_2,P61_13_1,P61_13_2,P61_14_1,P61_14_2,P61_15_1,P61_16_1,P61_20_1,P61_21_1
11134,026095,C061,1,E06,1,01,01,RE,01,RE,04,RE,1,11,17,1
11135,026095,C061,2,E06,1,01,01,RE,01,RE,04,RE,1,4,20,1
11136,026095,C061,3,E06,1,01,01,RE,01,RE,04,RE,1,14,16,2
11137,026095,C061,4,E06,1,01,01,RE,01,RE,04,RE,1,0,17,2
11138,026095,C061,5,E06,1,01,01,RE,01,RE,04,RE,1,1,16,2
11139,026095,C061,6,E06,1,01,01,RE,01,RE,04,RE,1,1,23,1
11140,026095,C061,7,E03,1,01,01,RE,01,RE,04,RE,1,1,25,1
11141,026095,C061,8,E03,1,01,01,RE,01,RE,04,RE,1,0,20,1
11142,026095,C061,9,E04,1,01,01,RE,01,RE,04,RE,1,0,19,1
11143,026095,C061,10,E04,1,01,01,RE,01,RE,04,RE,1,1,21,1
11144,026095,C061,11,E04,1,01,01,RE,01,RE,04,RE,1,0,14,1
11145,026095,C061,12,E07,2,01,06,MA,06,MA,04,MA,1,0,0,0
11146,026095,C061,13,E07,2,01,06,MA,06,MA,04,MA,1,0,0,0
11147,026095,C061,14,E07,2,01,06,MA,06,MA,04,MA,1,0,0,0
11148,026095,C061,15,E07,2,01,06,MA,06,MA,04,MA,1,0,0,0
11149,026095,C061,16,E07,2,01,06,MA,06,MA,04,MA,1,0,0,0
11150,026095,C061,17,E10,1,01,06,MA,06,MA,04,MA,1,0,20,1
11151,026095,C061,18,E11,1,01,06,MA,06,MA,04,MA,1,0,0,1